import { createFileRoute, useParams } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Logo } from "@/components/brand/Logo";
import { Money } from "@/components/brand/Money";
import { StatusPip } from "@/components/brand/StatusPip";
import { corridorLabel, formatPUSD, shortAddr, solscanUrl } from "@/lib/format";
import { CheckCircle2, ExternalLink } from "lucide-react";

export const Route = createFileRoute("/r/$id")({
  head: () => ({ meta: [{ title: "Receipt — Soté" }] }),
  component: PublicReceipt,
});

function PublicReceipt() {
  const { id } = useParams({ from: "/r/$id" });
  const [inv, setInv] = useState<any>(null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    supabase.from("invoices").select("*").eq("id", id).maybeSingle().then(({ data }) => {
      if (!data) setMissing(true); else setInv(data);
    });
  }, [id]);

  if (missing) return <div className="min-h-screen flex items-center justify-center text-sm text-muted-foreground">Receipt not available.</div>;
  if (!inv) return <div className="min-h-screen flex items-center justify-center text-sm text-muted-foreground">Loading…</div>;

  return (
    <div className="min-h-screen bg-bone py-12 px-4">
      <div className="mx-auto max-w-xl rounded-2xl border border-border bg-paper shadow-[0_24px_60px_-30px_rgba(14,26,20,0.25)] p-8">
        <div className="flex items-center justify-between">
          <Logo />
          <StatusPip status={inv.status} />
        </div>
        <div className="mt-8 flex items-start gap-3">
          <CheckCircle2 className="h-6 w-6 text-success mt-1" />
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">You've been paid</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              <Money units={inv.amount_pusd} /> from <span className="font-medium">{inv.vendor_snapshot?.display_name ?? "an importer"}</span>
              {inv.reference && <> for <span className="mono text-xs">{inv.reference}</span></>}.
            </p>
          </div>
        </div>

        <div className="mt-8 grid grid-cols-2 gap-4 text-sm border-t border-border pt-6">
          <div><div className="text-xs text-muted-foreground">Corridor</div><div className="mt-0.5 font-medium">{corridorLabel(inv.corridor)}</div></div>
          <div><div className="text-xs text-muted-foreground">Amount</div><div className="mt-0.5 mono tabular">{formatPUSD(inv.amount_pusd)} PUSD</div></div>
          <div><div className="text-xs text-muted-foreground">Invoice ID</div><div className="mt-0.5 mono text-xs">{inv.id.slice(0, 8)}…</div></div>
          <div><div className="text-xs text-muted-foreground">Delivered</div><div className="mt-0.5">{inv.delivered_at ? new Date(inv.delivered_at).toLocaleString() : "—"}</div></div>
        </div>

        {inv.release_tx_signature && (
          <a href={solscanUrl(inv.release_tx_signature)} target="_blank" rel="noreferrer" className="mt-6 flex items-center justify-between rounded-lg border border-border bg-bone px-4 py-3 text-sm hover:border-ink/40">
            <span><span className="text-muted-foreground">Release tx:</span> <span className="mono ml-2">{shortAddr(inv.release_tx_signature, 6)}</span></span>
            <ExternalLink className="h-3.5 w-3.5 text-muted-foreground" />
          </a>
        )}

        <div className="mt-6 text-xs text-muted-foreground border-t border-border pt-4">
          This receipt is generated by Soté and verifiable on the Solana blockchain.
        </div>
      </div>
    </div>
  );
}
